upstream_package_name: mariadb-connector-c
downstream_package_name: mariadb-connector-c
actions:
  post-upstream-clone:
    #spec file
    - "wget https://src.fedoraproject.org/rpms/mariadb-connector-c/raw/main/f/mariadb-connector-c.spec -O mariadb-connector-c.spec"
    #configs
    - "wget https://src.fedoraproject.org/rpms/mariadb-connector-c/raw/main/f/client.cnf -O client.cnf"
    - "wget https://src.fedoraproject.org/rpms/mariadb-connector-c/raw/main/f/my.cnf.in -O my.cnf.in"
    #gets rid of the patches that start with upstream
    - "sed -Ei 's/^(Patch[0-9]*:[[:space:]]*upstream)/#\\1/' mariadb-connector-c.spec"
    #gets the uncommented patches and downloads them
    - bash -c 'while read -r line; do fname=$(echo "$line" | sed -E "s/^Patch[0-9]*:[[:space:]]*//"); wget "https://src.fedoraproject.org/rpms/mariadb-connector-c/raw/main/f/$fname"; done < <(grep -E "^[[:space:]]*Patch[0-9]*:[[:space:]]*" mariadb-connector-c.spec | grep -v "^[[:space:]]*#")'

osh_diff_scan_after_copr_build: true
csmock_args: "--cswrap-timeout=180"

srpm_build_deps: "wget"

jobs:
  - job: copr_build
    trigger: commit
    branch: throwaway
    targets: fedora-rawhide
